# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'CongRequest' do
    pod 'CongRequest', :git => 'https://github.com/harde1/CongRequest'
end

target 'CongRequestTests' do

end

target 'CongRequestUITests' do

end

